# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Financial Life Copilot - Financial Health Assessment Agent
==========================================================
This specialist agent calculates financial indicators, savings ratios, debt metrics,
evaluates emergency cash sufficiency, and assigns an overall health score (0-100).
It strictly avoids recommending commercial packages or specific credit/investment products.
"""

import logging
from enum import StrEnum

from google.adk.agents import Agent
from google.adk.models import Gemini
from pydantic import BaseModel, Field

logger = logging.getLogger("copilot.health_agent")


# --- 1. Output Schemas ---


class ScoreCategory(StrEnum):
    POOR = "poor"  # Score < 50
    FAIR = "fair"  # Score 50-69
    GOOD = "good"  # Score 70-84
    EXCELLENT = "excellent"  # Score 85-100


class HealthMetrics(BaseModel):
    net_worth: float = Field(description="Total assets minus total liabilities.")
    savings_rate: float = Field(
        description="Savings rate as a percentage of net monthly income."
    )
    debt_ratio: float = Field(
        description="Debt-to-income ratio representing monthly obligations relative to income."
    )
    emergency_fund_months: float = Field(
        description="Cash reserves divided by average monthly expenses."
    )
    adequacy_status: str = Field(
        description="Sufficiency evaluation (e.g., 'Critical', 'Adequate', 'Strong')."
    )
    financial_health_score: float = Field(
        description="Consolidated health indicator score from 0.0 to 100.0."
    )
    score_category: ScoreCategory = Field(
        description="Qualitative assessment label matching the score boundaries."
    )


class CalculationSteps(BaseModel):
    net_worth_math: str = Field(
        description="Calculation formula and values used for net worth."
    )
    savings_rate_math: str = Field(
        description="Calculation formula and values used for savings rate."
    )
    debt_ratio_math: str = Field(
        description="Calculation formula and values used for DTI ratio."
    )
    health_score_breakdown: str = Field(
        description="Explanation of the weights used to compute the final score."
    )


class FinancialHealthReport(BaseModel):
    """Consolidated assessment output generated by the health agent."""

    metrics: HealthMetrics
    calculations: CalculationSteps
    key_vulnerabilities: list[str] = Field(
        default_factory=list,
        description="Critical vulnerabilities found (e.g. low savings, high DTI).",
    )
    general_guidance: list[str] = Field(
        default_factory=list,
        description="Fiduciary structural suggestions (NO brand or product recommendations allowed).",
    )


# --- 2. Custom Health Analytics Tools ---


def compute_financial_health_metrics(
    total_assets: float,
    total_liabilities: float,
    net_monthly_income: float,
    monthly_expenses: float,
    monthly_debt_payments: float,
    liquid_reserves: float,
) -> dict:
    """Computes mathematical financial indicators.

    Args:
        total_assets: Sum of all user assets.
        total_liabilities: Sum of all liabilities.
        net_monthly_income: Monthly post-tax net income.
        monthly_expenses: Monthly core living expenses.
        monthly_debt_payments: Monthly debt service obligations (credit cards, loans, mortgages).
        liquid_reserves: Cash or near-cash cash balances.

    Returns:
        A dict of raw metrics for the agent to analyze and audit.
    """
    net_worth = total_assets - total_liabilities

    # Savings rate = (Net Income - Monthly Expenses) / Net Income
    savings_amount = net_monthly_income - monthly_expenses
    savings_rate = (
        (savings_amount / net_monthly_income) * 100.0 if net_monthly_income > 0 else 0.0
    )

    # Debt ratio = Monthly Debt Payments / Net Monthly Income
    debt_ratio = (
        (monthly_debt_payments / net_monthly_income) * 100.0
        if net_monthly_income > 0
        else 0.0
    )

    # Emergency reserves = Liquid Reserves / Monthly Expenses
    emergency_months = (
        liquid_reserves / monthly_expenses if monthly_expenses > 0 else 0.0
    )

    # Score algorithm (weighted):
    # - Savings Rate: 30% (perfect at 20%+)
    # - Debt-to-Income: 30% (perfect at <= 15%, declines to 0 at 50%+)
    # - Emergency Fund: 40% (perfect at 6 months, scale from 0 to 6)

    # Savings score (max 30)
    savings_score = min(30.0, max(0.0, (savings_rate / 20.0) * 30.0))

    # Debt score (max 30)
    debt_score = max(0.0, 30.0 - (debt_ratio / 50.0) * 30.0)

    # Emergency reserves score (max 40)
    reserve_score = min(40.0, (emergency_months / 6.0) * 40.0)

    total_score = round(savings_score + debt_score + reserve_score, 1)

    return {
        "net_worth": net_worth,
        "savings_rate_pct": round(savings_rate, 2),
        "debt_ratio_pct": round(debt_ratio, 2),
        "emergency_fund_months": round(emergency_months, 2),
        "health_score": min(100.0, max(0.0, total_score)),
    }


# --- 3. Prompt & Agent Setup ---

FINANCIAL_HEALTH_ASSESSMENT_PROMPT = """You are a Financial Health Assessment Agent.
Your job is to calculate personal finance ratios and produce a structured FinancialHealthReport.

Your calculations MUST use the `compute_financial_health_metrics` tool.
For calculations and explanations:
- Explain every formula clearly, showing the exact asset/liability/income numbers used.
- Assess emergency fund adequacy: 'Critical' (< 3 months), 'Adequate' (3-6 months), or 'Strong' (6+ months).
- Categorize the health score: Excellent (85-100), Good (70-84), Fair (50-69), or Poor (< 50).

Safety and Fiduciary Constraint:
- You are strictly FORBIDDEN from recommending specific commercial financial products, investment funds,
  banks, or loan packages (e.g. do NOT say 'refinance with SoFi' or 'buy Vanguard VTSAX').
- Provide only generic, structural guidance (e.g., 'prioritize paying down high-interest credit card debt exceeding 15%',
  'aim to increase cash reserves to cover at least 3 months of core expenditures').
"""

financial_health_assessment_agent = Agent(
    name="financial_health_assessment_agent",
    model=Gemini(model="gemini-2.5-flash"),
    mode="task",
    output_schema=FinancialHealthReport,
    output_key="health_assessment",
    instruction=FINANCIAL_HEALTH_ASSESSMENT_PROMPT,
    tools=[compute_financial_health_metrics],
)
